# Generated by Django 2.0.3 on 2018-03-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routerinterface',
            unique_together={('network', 'router')},
        ),
    ]
