# Generated by Django 2.0.5 on 2018-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControllerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetask',
            name='username',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networktask',
            name='username',
            field=models.CharField(default='maged', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routertask',
            name='username',
            field=models.CharField(default='maged', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmtask',
            name='username',
            field=models.CharField(default='maged', max_length=200),
            preserve_default=False,
        ),
    ]
