# Generated by Django 2.0.5 on 2018-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControllerAPI', '0002_auto_20180602_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacetask',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networktask',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routertask',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vmtask',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
