# Generated by Django 2.0.5 on 2018-06-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControllerAPI', '0003_auto_20180617_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmtask',
            name='oldConf',
            field=models.TextField(default=''),
        ),
    ]
