# Generated by Django 2.0.2 on 2018-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('finished', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('objectName', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=20)),
                ('task', models.TextField()),
            ],
        ),
    ]
