# Generated by Django 2.0.3 on 2018-03-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControllerAPI', '0003_auto_20180322_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='interfaceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('objectNetwork', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=20)),
                ('task', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='routerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('objectName', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=20)),
                ('task', models.TextField()),
            ],
        ),
    ]
